### ISSUE TITLE
Add search query

### ISSUE THREAD

**Issue by DRYN07** [tarikjaber/Bulk-URL-Opener#3]
Can I add search quries to the url and search in multiple site at once? 

q=%s

**Comment by eaglezoli** [comment]
Same!

**Comment by tarikjaber** [comment]
I've switched to linux recently and no longer use this extension regularly.

I'll will try and implement this tomorrow though.

I'm thinking to hand it off to someone else (could be one you) for the long term though. Let me know if you or someone else would be interested in maintaining this extension.

**Comment by tarikjaber** [comment]
After looking into this I have this working: 

```yaml
- name: demo
  tabs:
    - https://www.google.com
    - https://www.youtube.com
- name: demo2
  tabs:
    - https://www.youtube.com
    - https://www.google.com
    - https://www.wikipedia.com
    - https://www.github.com
- name: demo3
  query: test
  tabs:
    - https://www.youtube.com/results?search_query=%s
    - https://www.google.com/search?q=%s
    - https://www.wikipedia.com
    - https://www.github.com
```

`demo3` opens youtube and google with the `%s` substituted for `test`. But this is not versatile as you can't input your own searches in the flow launcher bar.

I was thinking to get the query and split it by spaces. The first part would match tab group names. The second and subsequent parts are used for the search query.

**Comment by tarikjaber** [comment]
Released version 1.1.1 where you can query by typing words after the group. 

## Searching in flow searchbox
`bu demo3 hello world` would substitute "%s" for "hello world" for all URLs.

## Static/Default search
For a given tab group you can add a `query` key value pair as a default query.

```yaml
- name: demo3
  query: test
  tabs:
    - https://www.youtube.com/results?search_query=%s
    - https://www.google.com/search?q=%s
    - https://www.wikipedia.com
    - https://www.github.com
```

If you don't type a query then "%s" will be replaced with "test".
